package com.cf.bsot.model.pojo;

import java.util.Date;

/**
 * 定时任务实体类
 *
 * @author cf
 * @version 1.0
 * @date 2020/10/11 18:01
 */
public class QuartzJob {

    public static final String JOB_KEY = "JOB_KEY";

    private Long jobId;

    private String beanName;

    private String cronExpression;

    private Integer isStop;

    private String jobName;

    private String methodName;

    private String params;

    private String description;

    private String personInCharge;

    private String email;

    private String subTask;

    private Boolean pauseAfterFailure;

    private String createBy;

    private String updateBy;

    private Date createTime;

    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.job_id
     *
     * @return the value of s_bsot_quartz_job.job_id
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.job_id
     *
     * @param jobId the value for s_bsot_quartz_job.job_id
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.bean_name
     *
     * @return the value of s_bsot_quartz_job.bean_name
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getBeanName() {
        return beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.bean_name
     *
     * @param beanName the value for s_bsot_quartz_job.bean_name
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setBeanName(String beanName) {
        this.beanName = beanName == null ? null : beanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.cron_expression
     *
     * @return the value of s_bsot_quartz_job.cron_expression
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.cron_expression
     *
     * @param cronExpression the value for s_bsot_quartz_job.cron_expression
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.is_stop
     *
     * @return the value of s_bsot_quartz_job.is_stop
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public Integer getIsStop() {
        return isStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.is_stop
     *
     * @param isStop the value for s_bsot_quartz_job.is_stop
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setIsStop(Integer isStop) {
        this.isStop = isStop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.job_name
     *
     * @return the value of s_bsot_quartz_job.job_name
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.job_name
     *
     * @param jobName the value for s_bsot_quartz_job.job_name
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.method_name
     *
     * @return the value of s_bsot_quartz_job.method_name
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.method_name
     *
     * @param methodName the value for s_bsot_quartz_job.method_name
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.params
     *
     * @return the value of s_bsot_quartz_job.params
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.params
     *
     * @param params the value for s_bsot_quartz_job.params
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.description
     *
     * @return the value of s_bsot_quartz_job.description
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.description
     *
     * @param description the value for s_bsot_quartz_job.description
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.person_in_charge
     *
     * @return the value of s_bsot_quartz_job.person_in_charge
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getPersonInCharge() {
        return personInCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.person_in_charge
     *
     * @param personInCharge the value for s_bsot_quartz_job.person_in_charge
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setPersonInCharge(String personInCharge) {
        this.personInCharge = personInCharge == null ? null : personInCharge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.email
     *
     * @return the value of s_bsot_quartz_job.email
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.email
     *
     * @param email the value for s_bsot_quartz_job.email
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.sub_task
     *
     * @return the value of s_bsot_quartz_job.sub_task
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getSubTask() {
        return subTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.sub_task
     *
     * @param subTask the value for s_bsot_quartz_job.sub_task
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setSubTask(String subTask) {
        this.subTask = subTask == null ? null : subTask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.pause_after_failure
     *
     * @return the value of s_bsot_quartz_job.pause_after_failure
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public Boolean getPauseAfterFailure() {
        return pauseAfterFailure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.pause_after_failure
     *
     * @param pauseAfterFailure the value for s_bsot_quartz_job.pause_after_failure
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setPauseAfterFailure(Boolean pauseAfterFailure) {
        this.pauseAfterFailure = pauseAfterFailure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.create_by
     *
     * @return the value of s_bsot_quartz_job.create_by
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.create_by
     *
     * @param createBy the value for s_bsot_quartz_job.create_by
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.update_by
     *
     * @return the value of s_bsot_quartz_job.update_by
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.update_by
     *
     * @param updateBy the value for s_bsot_quartz_job.update_by
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.create_time
     *
     * @return the value of s_bsot_quartz_job.create_time
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.create_time
     *
     * @param createTime the value for s_bsot_quartz_job.create_time
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_bsot_quartz_job.update_time
     *
     * @return the value of s_bsot_quartz_job.update_time
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_bsot_quartz_job.update_time
     *
     * @param updateTime the value for s_bsot_quartz_job.update_time
     *
     * @mbg.generated Sun Oct 11 15:21:37 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}